from django.urls import path
from .views import (
    login_view, 
    logout_view, 
    register_view, 
    profile_view,
    change_password_view,
    author_link_view,
    author_search_api,
    publication_search_api,
    create_author_link_request,
    author_link_request_list_view,
    approve_author_link_request,
    reject_author_link_request,
    approve_selected_author_link_requests,
    author_link_evidence_api,
    cancel_author_link_request,
    my_publications,
    user_list,
    toggle_user_status,
    create_user,
    edit_user,
    department_list,
    create_department,
    update_department,
    delete_department,
    sql_execute_view,
    execute_sql,
    login_log_list,
    delete_login_log,
    clear_login_logs,
    login_log_api,
    author_list,
    author_list_api,
    university_list,
    university_list_api
)

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path("register/",register_view, name="register"),
    path("profile/", profile_view, name="profile"),
    path("change-password/", change_password_view, name="change_password"),
    path("author-link/", author_link_view, name="author_link"),
    path("api/authors/search/", author_search_api, name="author_search_api"),
    path("api/publications/search/", publication_search_api, name="publication_search_api"),
    path("api/author-link/create/", create_author_link_request, name="create_author_link_request"),
    path("admin/author-link-requests/", author_link_request_list_view, name="author_link_request_list"),
    path("admin/author-link-request/<int:request_id>/approve/", approve_author_link_request, name="approve_author_link_request"),
    path("admin/author-link-request/<int:request_id>/reject/", reject_author_link_request, name="reject_author_link_request"),
    path("admin/author-link-request/approve-selected/", approve_selected_author_link_requests, name="approve_selected_author_link_requests"),
    path("admin/author-link-request/<int:request_id>/evidence/", author_link_evidence_api, name="author_link_evidence_api"),
    path("author-link-request/<int:request_id>/cancel/", cancel_author_link_request, name="cancel_author_link_request"),
    path("my-publications/", my_publications, name="my_publications"),
    path("admin/users/", user_list, name="user_list"),
    path("admin/users/<int:user_id>/toggle-status/", toggle_user_status, name="toggle_user_status"),
    path("admin/users/create/",create_user, name="create_user"),
    path("admin/users/<int:user_id>/edit/", edit_user, name="edit_user"),
    path("admin/departments/", department_list, name="department_list"),
    path("admin/departments/create/", create_department, name="create_department"),
    path("admin/departments/<int:department_id>/update/", update_department, name="update_department"),
    path("admin/departments/<int:department_id>/delete/", delete_department, name="delete_department"),
    path('admin/login-logs/', login_log_list, name='sys_logs'),
    path('admin/sql-execute/', sql_execute_view, name='exec_sql'),
    path("admin/sql-execute/run/", execute_sql, name="execute_sql"),
    path("admin/login-logs/<int:log_id>/delete/", delete_login_log, name="delete_login_log"),
    path("admin/login-logs/clear/", clear_login_logs, name="clear_login_logs"),
    path("admin/login-logs/api/", login_log_api, name="login_log_api"),
    path("admin/authors/", author_list, name="author_list"),
    path("admin/authors/api/", author_list_api, name="author_list_api"),
    path("admin/universities/", university_list, name="university_list"),
    path("admin/universities/api/", university_list_api, name="university_list_api"),

]