# Generated by Django 6.0.4 on 2026-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
        ("users", "0002_authorlinkrequest_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorlinkrequest",
            name="publication",
        ),
        migrations.AddField(
            model_name="authorlinkrequest",
            name="publication",
            field=models.ManyToManyField(blank=True, to="dashboard.factpublication"),
        ),
    ]
