# Generated by Django 6.0.4 on 2026-06-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_authorlinkrequest_publication_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorlinkrequest",
            old_name="publication",
            new_name="evidence_publications",
        ),
    ]
