# Generated by Django 6.0.4 on 2026-06-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_publicationraw_authors"),
        ("users", "0004_rename_publication_authorlinkrequest_evidence_publications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorlinkrequest",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.author",
            ),
        ),
    ]
