# Generated by Django 6.0.4 on 2026-06-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_authorlinkrequest_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("fullname", models.CharField(max_length=200)),
                ("login_time", models.DateTimeField()),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-login_time"],
            },
        ),
    ]
