# Generated by Django 6.0.4 on 2026-05-11 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("iso_code", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500, unique=True)),
                ("issn", models.CharField(blank=True, max_length=100, null=True)),
                ("eissn", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("inserted_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutions",
                        to="dashboard.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                (
                    "orcid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authors",
                        to="dashboard.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="PublicationRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("year", models.IntegerField(blank=True, null=True)),
                ("source_title", models.TextField(blank=True, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("cited_by", models.IntegerField(default=0)),
                ("author_affiliations", models.TextField(blank=True, null=True)),
                ("correspondence_address", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "subfield",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "openalex_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("openalex_enriched", models.BooleanField(default=False)),
                ("openalex_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citation_group",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("citation_updated_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField()),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="dashboard.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="FactPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("year", models.IntegerField(db_index=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("cited_by", models.IntegerField(default=0)),
                (
                    "citation_group",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("citation_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("author_count", models.IntegerField(default=0)),
                ("is_international_collaboration", models.BooleanField(default=False)),
                ("country_count", models.IntegerField(default=0)),
                ("institution_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="dashboard.fieldgroup",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="dashboard.journal",
                    ),
                ),
                (
                    "raw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact",
                        to="dashboard.publicationraw",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-cited_by"],
            },
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["doi"], name="dashboard_p_doi_7ef7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["year"], name="dashboard_p_year_a9953c_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["field"], name="dashboard_p_field_fb592d_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(
                fields=["subfield"], name="dashboard_p_subfiel_f3cd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(
                fields=["citation_group"], name="dashboard_p_citatio_593f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(fields=["year"], name="dashboard_f_year_71909a_idx"),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["citation_group"], name="dashboard_f_citatio_5b10d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["field_group"], name="dashboard_f_field_g_565bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["cited_by"], name="dashboard_f_cited_b_d81f13_idx"
            ),
        ),
    ]
