# Generated by Django 6.0.4 on 2026-06-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationauthor",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_authors",
                to="dashboard.author",
            ),
        ),
        migrations.AddField(
            model_name="publicationauthor",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_authors",
                to="dashboard.factpublication",
            ),
        ),
        migrations.AddField(
            model_name="publicationraw",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="dashboard.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="publication_raw",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fact",
                to="dashboard.publicationraw",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="universities",
                to="dashboard.country",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authors",
                to="dashboard.university",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicationauthor",
            unique_together={("publication", "author")},
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["doi"], name="dashboard_p_doi_7ef7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["year"], name="dashboard_p_year_a9953c_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(fields=["field"], name="dashboard_p_field_fb592d_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(
                fields=["subfield"], name="dashboard_p_subfiel_f3cd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(
                fields=["processed"], name="dashboard_p_process_6138dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(fields=["year"], name="dashboard_f_year_71909a_idx"),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["field_group"], name="dashboard_f_field_g_b2ea7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["citation_group"], name="dashboard_f_citatio_5b10d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["document_type"], name="dashboard_f_documen_67610e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_first_author"], name="dashboard_f_is_firs_ec48f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_corresponding"], name="dashboard_f_is_corr_8d86c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_coauthored"], name="dashboard_f_is_coau_0798c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_international_collaboration"],
                name="dashboard_f_is_inte_37dc0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_domestic_collaboration"],
                name="dashboard_f_is_dome_9b3ee9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("name", "university")},
        ),
    ]
