# Generated by Django 6.0.4 on 2026-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="factpublication",
            new_name="dashboard_f_field_g_b2ea7a_idx",
            old_name="dashboard_f_field_g_565bca_idx",
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="field_group",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
