# Generated by Django 6.0.4 on 2026-05-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_rename_dashboard_f_field_g_565bca_idx_dashboard_f_field_g_b2ea7a_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="publicationraw",
            name="dashboard_p_citatio_593f12_idx",
        ),
        migrations.RenameField(
            model_name="publicationraw",
            old_name="citation_updated_at",
            new_name="processed_at",
        ),
        migrations.AddField(
            model_name="publicationraw",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="publicationraw",
            index=models.Index(
                fields=["processed"], name="dashboard_p_process_6138dc_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="publicationraw",
            name="citation_group",
        ),
    ]
