# Generated by Django 6.0.4 on 2026-06-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factpublication",
            name="eid",
        ),
        migrations.AddField(
            model_name="factpublication",
            name="authors_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
