# Generated by Django 6.0.4 on 2026-05-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0003_remove_publicationraw_dashboard_p_citatio_593f12_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationraw",
            name="openalex_enriched",
        ),
    ]
