# Generated by Django 6.0.4 on 2026-06-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_factpublication_eid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factpublication",
            name="eid",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
