# Generated by Django 6.0.4 on 2026-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_publicationraw_openalex_enriched"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factpublication",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="factpublication",
            name="dashboard_f_cited_b_d81f13_idx",
        ),
        migrations.RenameField(
            model_name="factpublication",
            old_name="raw",
            new_name="publication_raw",
        ),
        migrations.AddField(
            model_name="factpublication",
            name="is_coauthored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="is_corresponding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="is_domestic_collaboration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="is_first_author",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="transformed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="author_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="citation_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="field_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="factpublication",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["document_type"], name="dashboard_f_documen_67610e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_first_author"], name="dashboard_f_is_firs_ec48f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_corresponding"], name="dashboard_f_is_corr_8d86c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_coauthored"], name="dashboard_f_is_coau_0798c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_international_collaboration"],
                name="dashboard_f_is_inte_37dc0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factpublication",
            index=models.Index(
                fields=["is_domestic_collaboration"],
                name="dashboard_f_is_dome_9b3ee9_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="factpublication",
            name="citation_updated_at",
        ),
        migrations.RemoveField(
            model_name="factpublication",
            name="country_count",
        ),
        migrations.RemoveField(
            model_name="factpublication",
            name="institution_count",
        ),
        migrations.RemoveField(
            model_name="factpublication",
            name="journal",
        ),
    ]
