# Generated by Django 6.0.4 on 2026-06-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_factpublication_eid"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationraw",
            name="authors",
            field=models.TextField(blank=True, null=True),
        ),
    ]
