# Generated by Django 6.0.4 on 2026-05-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_factpublication_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dim_university",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="author",
            name="institution",
        ),
        migrations.DeleteModel(
            name="FieldGroup",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="country",
        ),
        migrations.DeleteModel(
            name="Journal",
        ),
        migrations.RemoveField(
            model_name="country",
            name="iso_code",
        ),
        migrations.AddField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name="country",
            table="dim_country",
        ),
        migrations.AddField(
            model_name="university",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="universities",
                to="dashboard.country",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Institution",
        ),
    ]
