# Generated by Django 6.0.4 on 2026-06-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_publicationraw_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="factpublication",
            name="journal",
            field=models.TextField(blank=True, null=True),
        ),
    ]
