# Generated by Django 6.0.4 on 2026-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_factpublication_journal"),
    ]

    operations = [
        migrations.AddField(
            model_name="factpublication",
            name="colab_country_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="colab_domestic_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="colab_international_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factpublication",
            name="total_colab_count",
            field=models.IntegerField(default=0),
        ),
    ]
