# Generated by Django 6.0.4 on 2026-05-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_author_publicationauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationraw",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
