# Generated by Django 6.0.4 on 2026-05-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_publicationraw_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="current_step",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_current",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="progress_total",
            field=models.IntegerField(default=0),
        ),
    ]
