# Generated by Django 6.0.4 on 2026-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_importbatch_current_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="uploaded_file",
            field=models.FileField(default="imports", upload_to="imports/%Y/%m/"),
        ),
    ]
