# Generated by Django 6.0.4 on 2026-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_importbatch_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="notes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
