# Generated by Django 6.0.4 on 2026-05-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_importbatch_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importbatch",
            old_name="failed_count",
            new_name="doi_missing_count",
        ),
        migrations.RenameField(
            model_name="importbatch",
            old_name="skipped_count",
            new_name="duplicated_count",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="notes",
        ),
    ]
