# Generated by Django 6.0.4 on 2026-05-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0012_rename_failed_count_importbatch_doi_missing_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="enriched_failed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="enriched_success",
            field=models.IntegerField(default=0),
        ),
    ]
