# Generated by Django 6.0.4 on 2026-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_importbatch_enriched_failed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="existing_doi_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="new_doi_count",
            field=models.IntegerField(default=0),
        ),
    ]
