# Generated by Django 6.0.4 on 2026-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_importbatch_existing_doi_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationraw",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
