# Generated by Django 6.0.4 on 2026-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_publicationraw_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="data_updated_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
