from .register import *
from .login import *
from .logout import *
from .profile import *
from .change_password import *
from .author_link import *
from .author_link_request_list import *
from .my_publications import *
from .user_management import *
from .department_list import *
from .sql_execute import *
from .logs import *
from .author_list import *
from .university_list import *
from .import_batch_list import *